### PR TITLE
fix(rpm): don't panic when parse source rpm name failed

### LINKED ISSUE #212: Source RPM names are parsed without verifying that they match the expected format
If a source RPM file name with an unexpected format is encountered, a rather unhelpful error message is thrown, as it could not be split into a name, a version, a release and an arch.

**Actual result:**
panic: runtime error: slice bounds out of range [:-1]

goroutine 86 [running]:
github.com/aquasecurity/fanal/analyzer/pkg/rpm.splitFileName(0xc006651ac0, 0x1a, 0xc0005f4570, 0x4, 0xc0005f4575, 0x4, 0xc0005f457a, 0x6)
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210711090115-306da65306b4/analyzer/pkg/rpm/rpm.go:123 +0x1f1
github.com/aquasecurity/fanal/analyzer/pkg/rpm.rpmPkgAnalyzer.parsePkgInfo(0xc004e56000, 0x678000, 0x6f0000, 0xc00fff0000, 0x33, 0x45, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210711090115-306da65306b4/analyzer/pkg/rpm/rpm.go:84 +0x72e
github.com/aquasecurity/fanal/analyzer/pkg/rpm.rpmPkgAnalyzer.Analyze(0x0, 0x0, 0xc000041938, 0x14, 0xc004e56000, 0x678000, 0x6f0000, 0x2, 0xc000121738, 0x609dfa)
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210711090115-306da65306b4/analyzer/pkg/rpm/rpm.go:31 +0x4c
github.com/aquasecurity/fanal/analyzer.Analyzer.AnalyzeFile.func1(0xc0003f83c0, 0xc000838030, 0xc000453320, 0x1d2f108, 0x2860b98, 0x0, 0x0, 0xc000041938, 0x14, 0xc004e56000, ...)
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210711090115-306da65306b4/analyzer/analyzer.go:208 +0xe6
created by github.com/aquasecurity/fanal/analyzer.Analyzer.AnalyzeFile
        /home/runner/go/pkg/mod/github.com/aquasecurity/fanal@v0.0.0-20210711090115-306da65306b4/analyzer/analyzer.go:204 +0x333

**Expected result:**
Source RPM 'malformed-1.2.3-1-src.rpm' has an unexpected name format. The expected format is name-version-release.arch(.rpm). This RPM will be skipped.
[Scan continues with the next RPM]

**Background:**
As of 2021.07.21, the Rpm gradle task (from gradle-ospackage-plugin), when the source rpm name is left unspecified, defaults it to end with -src.rpm (as far as I know, that does not follow rpm naming conventions and is probably a bug).
Given that this is a default value, plus, how source rpms can go under the radar of many, and that the current error message does not state which rpm caused the problem, makes the issue immensely tough to debug.

### PR DESCRIPTION
**Pull request by mozillazg**
https://github.com/aquasecurity/trivy/issues/1172  
Fixes #212

Before:

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 2306 [running]:
github.com/aquasecurity/fanal/analyzer/pkg/rpm.splitFileName(0xc00004ad80, 0x1a, 0x50, 0xc002347000, 0x50, 0x50, 0xc0006bdc2f, 0x6)
        /go/src/github.com/aquasecurity/fanal/analyzer/pkg/rpm/rpm.go:133 +0x1f1
github.cogor/pkg/rpm.rpmPkgAnalyzer.parsePkgInfo(0xc00b75c000, 0x1211000, 0x1530000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/aquasecurity/fanal/analyzer/pkg/rpm/rpm.go:87 +0xb17
github.cogor/pkg/rpm.rpmPkgAnalyzer.Analyze(0x0, 0x0, 0xc002f194d0, 0x14, 0xc00b75c000, 0x1211000, 0x1530000, 0x2, 0xc009c6e4e0, 0x11eaeda)
        /go/src/github.com/aquasecurity/fanal/analyzer/pkg/rpm/rpm.go:31 +0x5a
github.cogor.Analyzer.AnalyzeFile.func1(0xc0008c8000, 0xc00013a350, 0xc0003aa000, 0x265b168, 0x3073f48, 0x0, 0x0, 0xc002f194d0, 0x14, 0xc00b75c000, ...)
        /go/src/github.com/aquasecurity/fanal/analyzer/analyzer.go:212 +0xe6
created bgonal/analyzer.Analyzer.AnalyzeFile
        /go/src/github.com/aquasecurity/fanal/analyzer/analyzer.go:208 +0x333
```

After:

```
2021/10/02 12:14:26 Invalid Source RPM Found: elasticsearch-5.6.16-1-src.rpm
```

### CODE REVIEW

File: analyzer/pkg/rpm/rpm_test.go [hunk 1]
```diff
@@ -598,3 +598,46 @@ func TestParseRpmInfo(t *testing.T) {
...
+			}
+			if gotName != tt.wantName {
+				t.Errorf("splitFileName() gotName = %v, want %v", gotName, tt.wantName)
+			}
+			if gotVer != tt.wantVer {
+				t.Errorf("splitFileName() gotVer = %v, want %v", gotVer, tt.wantVer)
+			}
+			if gotRel != tt.wantRel {
+				t.Errorf("splitFileName() gotRel = %v, want %v", gotRel, tt.wantRel)
+			}
```
Comment (knqyf263) [inline analyzer/pkg/rpm/rpm_test.go:640]: We use testify/assert

File: analyzer/pkg/rpm/rpm.go [hunk 2]
```diff
@@ -84,7 +87,10 @@ func (a rpmPkgAnalyzer) parsePkgInfo(packageBytes []byte) ([]types.Package, []st
 		var srcName, srcVer, srcRel string
 		if pkg.SourceRpm != "(none)" && pkg.SourceRpm != "" {
 			// source epoch is not included in SOURCERPM
-			srcName, srcVer, srcRel = splitFileName(pkg.SourceRpm)
+			srcName, srcVer, srcRel, err = splitFileName(pkg.SourceRpm)
+			if err != nil {
+				log.Printf("Invalid Source RPM Found: %s", pkg.SourceRpm)
```
Comment (knqyf263) [inline analyzer/pkg/rpm/rpm.go:92]: Please use the logger here.
https://github.com/aquasecurity/fanal/blob/main/log/log.go

```suggestion
				log.Logger.Debugf("Invalid Source RPM Found: %s", pkg.SourceRpm)
```

File: analyzer/pkg/rpm/rpm_test.go [hunk 3]
```diff
@@ -598,3 +598,46 @@ func TestParseRpmInfo(t *testing.T) {
...
+		{
+			name: "invalid name",
+			args: args{
+				filename: "elasticsearch-5.6.16-1-src.rpm",
+			},
+			wantName: "",
+			wantVer:  "",
+			wantRel:  "",
+			wantErr:  true,
+		},
```
Comment (knqyf263) [inline analyzer/pkg/rpm/rpm_test.go:623]: Could you add happy path as well?

File: analyzer/pkg/rpm/rpm_test.go [hunk 4]
```diff
@@ -598,3 +598,46 @@ func TestParseRpmInfo(t *testing.T) {
...
 	}
 }
+
+func Test_splitFileName(t *testing.T) {
+	type args struct {
+		filename string
+	}
+	tests := []struct {
+		name     string
+		args     args
```
Comment (knqyf263) [inline analyzer/pkg/rpm/rpm_test.go:608]: In this case, we can simply define `filename` here.

```suggestion
		filename string
```

File: analyzer/pkg/rpm/rpm.go [hunk 5]
```diff
@@ -24,6 +26,7 @@ var requiredFiles = []string{
 	"usr/lib/sysimage/rpm/Packages",
 	"var/lib/rpm/Packages",
 }
+var errUnexpectedNameFormat = errors.New("unexpected name format")
```
Comment (knqyf263) [inline analyzer/pkg/rpm/rpm.go:29]: For stacktrace, we still use xerrors.

```suggestion
var errUnexpectedNameFormat = xerrors.New("unexpected name format")
```

**Review by knqyf263 — CHANGES_REQUESTED** [review]
Thanks for the contribution!

**Comment by mozillazg** [comment]
@knqyf263 Thanks for your review! Please check again.

**Review by knqyf263 — APPROVED** [review]
Thanks a lot!
